site_name: PINES
repo_url: https://github.com/CEDARS-NLP/PINES

nav:
  - Overview: README.md # will not work if deployed from windows as windows do not respect symlinks
  - About: ABOUT.md
  - User Manual: PINES_user_manual.md
  - API Reference: API_reference.md
  - Terms of Use: TERMS_OF_USE.md # this will have to be linked back to package root ../, do NOT transfer this file to the repo
 

theme: 
  name: readthedocs
  include_homepage_in_sidebar: true
  prev_next_buttons_location: none
  titles_only: false
  logo: pics/pine_M_centered.png

plugins: 
  - search
  - mkdocstrings
  - bibtex:
      bib_file: "refs.bib"
  - swagger-ui-tag
  
markdown_extensions:
  - footnotes
  
extra_css:
  - style.css
