title: PINES
tagline: clinical event detection
email: singhrohan@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A NLP package based on transformers to detect clinical events in patient notes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cedars-nlp.github.io/PINES" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ygivenx
github_username:  ygivenx

# Build settings
# theme: minima
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Aux links for the upper right navigation
aux_links:
  "PINES on GitHub":
    - "https://github.com/CEDARS-NLP/PINES"
